version: '3.8'
services:
 go-aws-dynamo-local:
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   image: "amazon/dynamodb-local:latest"
   container_name: go-aws-dynamo-local
   ports:
     - "8000:8000"
   volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal
 dynamodb-admin-gui:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"  
    environment:
      DYNAMO_ENDPOINT: "http://go-aws-dynamo-local:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local     
    depends_on:
      - go-aws-dynamo-local 
# app:
#    image: golang:1.21-alpine
#    environment:
#      DYNAMO_ENDPOINT: "http://go-aws-dynamo-local:8000"    
#    volumes:
#      - ./:/app
#    working_dir: /app
#    command: sh -c "go run ./cmd/main.go"         
#    depends_on:
#      - go-aws-dynamo-local  